# Uses Shopify's blog feature to create artist bios

# Get all artists by getting all articles in the blog
query GetAllArtists($blogHandle: String!, $first: Int = 12, $after: String) {
  blog(handle: $blogHandle) {
    id
    handle
    articles(first: $first, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        node {
          id
          title
          handle
          contentHtml
          image {
            url
            altText
          }
        }
      }
    }
  }
}

# Get an artist's details by getting their article in the blog
query GetArtist($blogHandle: String!, $articleHandle: String!) {
  blog(handle: $blogHandle) {
    articleByHandle(handle: $articleHandle) {
      id
      title
      handle
      contentHtml
      image {
        url
        altText
      }
    }
  }
}
