query GetAllCollections {
  collections(first: 10) {
    edges {
      node {
        id
        handle
        title
      }
      cursor
    }
  }
}

query GetCollectionWithProducts(
  $collectionHandle: String!
  $productsFirst: Int = 12
  $productsAfter: String
  $imagesFirst: Int = 5
  $artistNamespace: String = "custom"
  $artistKey: String = "artist"
  $genreNamespace: String = "custom"
  $genreKey: String = "genre"
) {
  collection(handle: $collectionHandle) {
    title
    products(first: $productsFirst, after: $productsAfter) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          handle
          images(first: $imagesFirst) {
            edges {
              node {
                id
                url
                altText
                width
                height
              }
            }
          }
          artist: metafield(namespace: $artistNamespace, key: $artistKey) {
            value
            type
          }
          genre: metafield(namespace: $genreNamespace, key: $genreKey) {
            value
            type
          }
        }
      }
    }
  }
}
