query GetAllProducts(
  $first: Int = 12
  $after: String
  $imagesFirst: Int = 1
  $artistNamespace: String = "custom"
  $artistKey: String = "artist"
  $genreNamespace: String = "custom"
  $genreKey: String = "genre"
) {
  products(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      cursor
      node {
        id
        title
        handle
        createdAt
        descriptionHtml
        images(first: $imagesFirst) {
          edges {
            node {
              id
              url
              altText
              width
              height
            }
          }
        }
        priceRange {
          minVariantPrice {
            amount
            currencyCode
          }
        }
        artist: metafield(namespace: $artistNamespace, key: $artistKey) {
          value
          type
        }
        genre: metafield(namespace: $genreNamespace, key: $genreKey) {
          value
          type
        }
      }
    }
  }
}

query GetRecentProducts(
  $first: Int = 6
  $sortKey: ProductSortKeys = CREATED_AT
  $reverse: Boolean = true
  $imagesFirst: Int = 1
  $artistNamespace: String = "custom"
  $artistKey: String = "artist"
  $genreNamespace: String = "custom"
  $genreKey: String = "genre"
) {
  products(first: $first, sortKey: $sortKey, reverse: $reverse) {
    edges {
      cursor
      node {
        id
        title
        handle
        createdAt
        descriptionHtml
        images(first: $imagesFirst) {
          edges {
            node {
              id
              url
              altText
              width
              height
            }
          }
        }
        priceRange {
          minVariantPrice {
            amount
            currencyCode
          }
        }
        artist: metafield(namespace: $artistNamespace, key: $artistKey) {
          value
          type
        }
        genre: metafield(namespace: $genreNamespace, key: $genreKey) {
          value
          type
        }
      }
    }
  }
}

query GetCollectionProducts(
  $collectionHandle: String!
  $productsFirst: Int = 12
  $productsAfter: String
  $imagesFirst: Int = 1
  $artistNamespace: String = "custom"
  $artistKey: String = "artist"
  $genreNamespace: String = "custom"
  $genreKey: String = "genre"
) {
  collectionByHandle(handle: $collectionHandle) {
    products(first: $productsFirst, after: $productsAfter) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          id
          title
          handle
          createdAt
          descriptionHtml
          images(first: $imagesFirst) {
            edges {
              node {
                id
                url
                altText
                width
                height
              }
            }
          }
          priceRange {
            minVariantPrice {
              amount
              currencyCode
            }
          }
          artist: metafield(namespace: $artistNamespace, key: $artistKey) {
            value
            type
          }
          genre: metafield(namespace: $genreNamespace, key: $genreKey) {
            value
            type
          }
        }
      }
    }
  }
}
